# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      'get-childitem $(build.artifactStagingDirectory) -recurse | Foreach { 
              $lastupdatetime=$_.LastWriteTime; 
              $nowtime=get-date; 
              if(($nowtime - $lastupdatetime).totalhours -le 24) { 
                Write-Host $_.fullname 
              } 
              else{ 
                remove-item $_.fullname -Recurse -Force 
              } 
            }'
            failOnStderr: true
            workingDirectory: '$(build.artifactStagingDirectory)'
    pwsh: true
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://ftp.dlptest.com/'
    username: 'dlpuser'
    password: 'rNrKYTX9g7z3RgJRmxWuGHbeu'
    rootDirectory: '$(Build.ArtifactStagingDirectory)'
    filePatterns: '**'
    remoteDirectory: '/FTP'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false