# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: '$(Build.Repository.LocalPath)'
    MachineNames: '192.168.242.1'
    AdminUserName: 'Ram'
    AdminPassword: 'Pass@123'
    TargetPath: 'c:\temp'